// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Untitled', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Untitled', async function() {
    await driver.get("http://103.203.132.254:8888/login")
    await driver.manage().window().setRect({ width: 1312, height: 741 })
    await driver.findElement(By.name("username")).click()
    await driver.findElement(By.name("username")).sendKeys("Admin")
    await driver.findElement(By.name("password")).sendKeys("password")
    await driver.findElement(By.css(".btn:nth-child(1)")).click()
    await driver.findElement(By.css(".nav-item:nth-child(3) p")).click()
    await driver.findElement(By.css("#sale-management .nav-item:nth-child(3) .sidebar-normal")).click()
    await driver.findElement(By.css("#vs1__combobox .vs__search")).click()
    await driver.findElement(By.id("vs1__option-0")).click()
    await driver.findElement(By.css(".form-group:nth-child(3) .form-control")).click()
    await driver.findElement(By.css(".form-group:nth-child(3) .form-control")).sendKeys("15,98")
    {
      const element = await driver.findElement(By.id("vs2__option-0"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.id("vs2__option-0"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.id("vs2__option-0"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".vs--open")).click()
    await driver.findElement(By.id("vs2__option-0")).click()
    await driver.findElement(By.css(".form-group:nth-child(5)")).click()
    await driver.findElement(By.css("#vs3__combobox .vs__search")).click()
    await driver.findElement(By.id("vs3__option-1")).click()
    await driver.findElement(By.css(".vs__search:nth-child(1)")).click()
    await driver.findElement(By.id("vs4__option-0")).click()
    await driver.findElement(By.name("selectPlan")).click()
    await driver.findElement(By.css(".form-group:nth-child(12) .form-control")).click()
    await driver.findElement(By.css(".form-group:nth-child(12) .form-control")).sendKeys("Order 1")
    await driver.findElement(By.css(".form-group:nth-child(13) .form-control")).click()
    await driver.findElement(By.css(".form-group:nth-child(13) .form-control")).sendKeys("0000")
    await driver.findElement(By.css(".form-group:nth-child(14) .form-control")).click()
    await driver.findElement(By.css(".form-group:nth-child(14) .form-control")).sendKeys("0998999988")
    await driver.findElement(By.css(".form-group:nth-child(17) .form-control")).click()
    await driver.findElement(By.css(".form-group:nth-child(17) .form-control")).sendKeys("Ygn")
    await driver.findElement(By.css(".btn")).click()
  })
})