// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Login form', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login form', async function() {
    // Test name: Login form
    // Step # | name | target | value
    // 1 | open | /login | 
    await driver.get("http://103.203.132.254:8888/login")
    // 4 | type | name=username | Admin
    await driver.findElement(By.name("username")).sendKeys("Admin")
    // 5 | type | name=password | password
    await driver.findElement(By.name("password")).sendKeys("password")
    // 6 | click | css=.btn:nth-child(1) | 
    await driver.findElement(By.css(".btn:nth-child(1)")).click()
    // 7 | click | css=.nav-item:nth-child(3) p | 
    await driver.findElement(By.css(".nav-item:nth-child(3) p")).click()
    // 8 | click | css=#sale-management .nav-item:nth-child(3) .sidebar-normal | 
    await driver.findElement(By.css("#sale-management .nav-item:nth-child(3) .sidebar-normal")).click()
  })
})
